<a href="https://colab.research.google.com/github/geojose911/Python-Basics/blob/main/Tip_Amount_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tip_data = pd.read_excel('/content/tip-amount.xlsx')
tip_data.head()

   Meal  Observed total bill(xi)  Observed tip amount(yi)
0     1                       34                        5
1     2                      108                       17
2     3                       64                       11
3     4                       88                        8
4     5                       99                       14

In [ ]:
tip_data.drop('Meal',axis=1,inplace=True)
tip_data.head()

   Observed total bill(xi)  Observed tip amount(yi)
0                       34                        5
1                      108                       17
2                       64                       11
3                       88                        8
4                       99                       14

In [ ]:
tip_data.corr()

                         Observed total bill(xi)  Observed tip amount(yi)
Observed total bill(xi)                 1.000000                 0.865665
Observed tip amount(yi)                 0.865665                 1.000000

In [ ]:
# feature - target splitting

y = tip_data['Observed tip amount(yi)']
X = tip_data.drop('Observed tip amount(yi)',axis=1)

In [ ]:
# train - test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
# creating linear regression model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train,y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print(y_pred)
print(y_test)

[ 4.31609993 13.55968078]
0     5
1    17
Name: Observed tip amount(yi), dtype: int64

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

6.151757829712871
0.8291178380635313

In [ ]:
# making prediction for 50$ bill amount
bill_pred = model.predict([[50]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
bill_pred

array([6.31471201])